/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register with e-mail and password; starts a session and a placement test */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        displayName: string;
                    };
                };
            };
            responses: {
                201: components["responses"]["Me"];
                409: components["responses"]["Problem"];
                429: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** E-mail/password login (rate limited; generic errors — OWASP A07) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["Me"];
                401: components["responses"]["Problem"];
                429: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin OAuth authorization-code flow (state + PKCE) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "github" | "google";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to provider consent screen */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth callback; creates/links account, starts session */
        get: {
            parameters: {
                query: {
                    code: string;
                    state: string;
                };
                header?: never;
                path: {
                    provider: "github" | "google";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect into the app (placement or dashboard) */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate the current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile, level, streaks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Me"];
                401: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placement/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the active placement session (resume support) or 404 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["PlacementState"];
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        /** Start (or restart, abandoning the active) placement session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                201: components["responses"]["PlacementState"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placement/session/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an answer; server scores it and returns next question or result */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        questionId: string;
                        answer: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["PlacementState"];
                /** @description Question already answered or session not active */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Modules grouped by level with lock state for the current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Track listing */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Module"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lesson with its ordered exercises (no correct answers included) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    lessonId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lesson detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lesson"];
                    };
                };
                /** @description Lesson's track is locked for this user (FR-006) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exerciseId}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a written/listening answer. Server validates (typo tolerance for writing per research R8), logs an immutable progress entry, updates streak and review queue. Idempotent by attemptId (offline outbox replay). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description client-generated
                         */
                        attemptId: string;
                        answer: string;
                        /**
                         * Format: date-time
                         * @description offline completion time
                         */
                        completedAt?: string;
                        /** @default false */
                        isReview?: boolean;
                    };
                };
            };
            responses: {
                /** @description Duplicate replay (already recorded) — same body as 201 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                201: components["responses"]["AttemptResult"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exerciseId}/speech-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a spoken attempt (≤30 s, ≤1.5 MB, audio/webm or audio/mp4). Server transcribes via primary provider with secondary failover (research R2), scores similarity (1−WER), logs progress. Rate limited per user. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: uuid */
                        attemptId: string;
                        /** Format: binary */
                        audio: string;
                    };
                };
            };
            responses: {
                /** @description Scored speaking result */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpeechResult"];
                    };
                };
                413: components["responses"]["Problem"];
                /** @description Audio unintelligible — retry prompted, not scored as failure */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                429: components["responses"]["Problem"];
                /** @description All transcription providers unavailable — client offers retry */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Streak, longest streak, XP, and 90-day heatmap buckets (user timezone) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard aggregate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dashboard"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Items due for spaced review (due_at <= now), oldest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Due review items with their exercises */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
        };
        User: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            displayName?: string;
            /** @enum {string|null} */
            proficiencyLevel?: "basic" | "intermediate" | "advanced" | null;
            currentStreak?: number;
            longestStreak?: number;
        };
        PlacementState: {
            /** @enum {string} */
            status: "active" | "completed";
            questionsServed: number;
            /** @enum {string} */
            currentBand?: "A1" | "A2" | "B1" | "B2" | "C1";
            /** @description Present while active; never includes the correct answer */
            nextQuestion?: {
                /** Format: uuid */
                id?: string;
                /** @enum {string} */
                questionType?: "choice" | "listening_choice" | "order";
                prompt?: string;
                options?: string[];
                audioAssetUrl?: string | null;
            } | null;
            /** @enum {string|null} */
            assignedLevel?: "basic" | "intermediate" | "advanced" | null;
        };
        Module: {
            /** Format: uuid */
            id?: string;
            title?: string;
            description?: string;
            /** @enum {string} */
            themeType?: "travel" | "tech";
            /** @enum {string} */
            difficultyLevel?: "basic" | "intermediate" | "advanced";
            /** @description true when above the user's level (FR-006) */
            locked?: boolean;
            lessons?: {
                /** Format: uuid */
                id?: string;
                title?: string;
                xpReward?: number;
                completed?: boolean;
            }[];
        };
        Lesson: {
            /** Format: uuid */
            id?: string;
            title?: string;
            pedagogicalFocus?: string;
            xpReward?: number;
            exercises?: {
                /** Format: uuid */
                id?: string;
                /** @enum {string} */
                exerciseType?: "translate" | "fill_blank" | "listening_choice" | "listening_order" | "speaking";
                promptContext?: string;
                options?: string[] | null;
                audioAssetUrl?: string | null;
                /** @description Only for speaking exercises (sentence to read aloud) */
                targetSentence?: string | null;
            }[];
        };
        AttemptResult: {
            correct?: boolean;
            accuracyScore?: number;
            toleratedTypos?: string[];
            /** @description shown when incorrect (US2 scenario 3) */
            expectedAnswer?: string | null;
            lessonCompleted?: boolean;
            xpAwarded?: number;
        };
        SpeechResult: {
            similarity?: number;
            /** @description similarity >= 0.80 (FR-014) */
            passed?: boolean;
            transcript?: string;
            /** @description omitted/unintelligible target words to highlight (FR-015) */
            missedWords?: string[];
            xpAwarded?: number;
        };
        Dashboard: {
            currentStreak?: number;
            longestStreak?: number;
            totalXp?: number;
            heatmap?: {
                /** Format: date */
                date?: string;
                interactions?: number;
                /** @description saturation bucket */
                level?: number;
            }[];
            dueReviews?: number;
        };
        ReviewItem: {
            /** Format: uuid */
            id?: string;
            exercise?: components["schemas"]["Lesson"]["exercises"]["items"];
            /** Format: date-time */
            dueAt?: string;
            failureCount?: number;
        };
    };
    responses: {
        /** @description Current user */
        Me: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        /** @description Placement progress — either the next question or the final result */
        PlacementState: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PlacementState"];
            };
        };
        /** @description Scored attempt */
        AttemptResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AttemptResult"];
            };
        };
        /** @description Error (RFC 9457) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
